version: '3.7'

services:
  run-up-database:
    image: mongo
    restart: always
    container_name: run-up-database
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
    name: db-network

volumes:
  mongo-data:
